// @ts-nocheck
/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), jsonSchema),
      z.array(jsonSchema),
    ])
    .nullable()
);

export const publicProfilesRowSchema = z.object({
  id: z.string(),
  display_name: z.string(),
  avatar_url: z.string().nullable(),
  bio: z.string().nullable(),
  identity_status: z.union([
    z.literal("unverified"),
    z.literal("pending"),
    z.literal("verified"),
    z.literal("rejected"),
  ]),
  location: z.string().nullable(),
  address_city: z.string().nullable(),
  address_country: z.string().nullable(),
  rating_avg: z.number(),
  rating_count: z.number(),
  response_time_avg_minutes: z.number().nullable(),
  completed_rentals: z.number(),
  payway_beneficiary_id: z.string().nullable(),
  bank_name: z.string().nullable(),
  bank_account_masked: z.string().nullable(),
  last_active_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const publicProfilesInsertSchema = z.object({
  id: z.string(),
  display_name: z.string(),
  avatar_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  identity_status: z
    .union([
      z.literal("unverified"),
      z.literal("pending"),
      z.literal("verified"),
      z.literal("rejected"),
    ])
    .optional(),
  location: z.string().optional().nullable(),
  address_city: z.string().optional().nullable(),
  address_country: z.string().optional().nullable(),
  rating_avg: z.number().optional(),
  rating_count: z.number().optional(),
  response_time_avg_minutes: z.number().optional().nullable(),
  completed_rentals: z.number().optional(),
  payway_beneficiary_id: z.string().optional().nullable(),
  bank_name: z.string().optional().nullable(),
  bank_account_masked: z.string().optional().nullable(),
  last_active_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicProfilesUpdateSchema = z.object({
  id: z.string().optional(),
  display_name: z.string().optional(),
  avatar_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  identity_status: z
    .union([
      z.literal("unverified"),
      z.literal("pending"),
      z.literal("verified"),
      z.literal("rejected"),
    ])
    .optional(),
  location: z.string().optional().nullable(),
  address_city: z.string().optional().nullable(),
  address_country: z.string().optional().nullable(),
  rating_avg: z.number().optional(),
  rating_count: z.number().optional(),
  response_time_avg_minutes: z.number().optional().nullable(),
  completed_rentals: z.number().optional(),
  payway_beneficiary_id: z.string().optional().nullable(),
  bank_name: z.string().optional().nullable(),
  bank_account_masked: z.string().optional().nullable(),
  last_active_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicCategoriesRowSchema = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullable(),
  icon: z.string().nullable(),
  parent_id: z.string().nullable(),
  sort_order: z.number(),
  created_at: z.string(),
});

export const publicCategoriesInsertSchema = z.object({
  id: z.string().optional(),
  name: z.string(),
  slug: z.string(),
  description: z.string().optional().nullable(),
  icon: z.string().optional().nullable(),
  parent_id: z.string().optional().nullable(),
  sort_order: z.number().optional(),
  created_at: z.string().optional(),
});

export const publicCategoriesUpdateSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  description: z.string().optional().nullable(),
  icon: z.string().optional().nullable(),
  parent_id: z.string().optional().nullable(),
  sort_order: z.number().optional(),
  created_at: z.string().optional(),
});

export const publicListingsRowSchema = z.object({
  id: z.string(),
  owner_id: z.string(),
  category_id: z.string().nullable(),
  title: z.string(),
  description: z.string().nullable(),
  type: z.union([z.literal("offer"), z.literal("request")]),
  status: z.union([
    z.literal("draft"),
    z.literal("active"),
    z.literal("paused"),
    z.literal("archived"),
  ]),
  price_hourly: z.number().nullable(),
  price_daily: z.number(),
  price_weekly: z.number().nullable(),
  deposit_amount: z.number(),
  currency: z.string(),
  location: z.string().nullable(),
  address_text: z.string().nullable(),
  address_city: z.string().nullable(),
  address_country: z.string().nullable(),
  availability_type: z.string(),
  min_rental_hours: z.number(),
  max_rental_days: z.number().nullable(),
  delivery_available: z.boolean(),
  delivery_fee: z.number(),
  pickup_available: z.boolean(),
  view_count: z.number(),
  rating_avg: z.number(),
  rating_count: z.number(),
  published_at: z.string().nullable(),
  deleted_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const publicListingsInsertSchema = z.object({
  id: z.string().optional(),
  owner_id: z.string(),
  category_id: z.string().optional().nullable(),
  title: z.string(),
  description: z.string().optional().nullable(),
  type: z.union([z.literal("offer"), z.literal("request")]).optional(),
  status: z
    .union([z.literal("draft"), z.literal("active"), z.literal("paused"), z.literal("archived")])
    .optional(),
  price_hourly: z.number().optional().nullable(),
  price_daily: z.number(),
  price_weekly: z.number().optional().nullable(),
  deposit_amount: z.number().optional(),
  currency: z.string().optional(),
  location: z.string().optional().nullable(),
  address_text: z.string().optional().nullable(),
  address_city: z.string().optional().nullable(),
  address_country: z.string().optional().nullable(),
  availability_type: z.string().optional(),
  min_rental_hours: z.number().optional(),
  max_rental_days: z.number().optional().nullable(),
  delivery_available: z.boolean().optional(),
  delivery_fee: z.number().optional(),
  pickup_available: z.boolean().optional(),
  view_count: z.number().optional(),
  rating_avg: z.number().optional(),
  rating_count: z.number().optional(),
  published_at: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicListingsUpdateSchema = z.record(z.string(), z.any());

export const publicListingMediaRowSchema = z.object({
  id: z.string(),
  listing_id: z.string(),
  url: z.string(),
  thumbnail_url: z.string().nullable(),
  sort_order: z.number(),
  is_primary: z.boolean(),
  created_at: z.string(),
});

export const publicListingMediaInsertSchema = z.object({
  id: z.string().optional(),
  listing_id: z.string(),
  url: z.string(),
  thumbnail_url: z.string().optional().nullable(),
  sort_order: z.number().optional(),
  is_primary: z.boolean().optional(),
  created_at: z.string().optional(),
});

export const publicListingMediaUpdateSchema = z.record(z.string(), z.any());

export const publicAvailabilityRowSchema = z.object({
  id: z.string(),
  listing_id: z.string(),
  start_time: z.string(),
  end_time: z.string(),
  is_available: z.boolean(),
  created_at: z.string(),
});

export const publicAvailabilityInsertSchema = z.object({
  id: z.string().optional(),
  listing_id: z.string(),
  start_time: z.string(),
  end_time: z.string(),
  is_available: z.boolean().optional(),
  created_at: z.string().optional(),
});

export const publicAvailabilityUpdateSchema = z.record(z.string(), z.any());

export const publicBookingsRowSchema = z.object({
  id: z.string(),
  listing_id: z.string(),
  renter_id: z.string(),
  owner_id: z.string(),
  start_time: z.string(),
  end_time: z.string(),
  status: z.union([
    z.literal("requested"),
    z.literal("approved"),
    z.literal("declined"),
    z.literal("auto_declined"),
    z.literal("active"),
    z.literal("completed"),
    z.literal("cancelled"),
    z.literal("disputed"),
    z.literal("resolved"),
  ]),
  payment_authorized: z.boolean(),
  subtotal: z.number(),
  service_fee: z.number(),
  delivery_fee: z.number(),
  protection_fee: z.number(),
  deposit_amount: z.number(),
  total_amount: z.number(),
  owner_payout: z.number(),
  currency: z.string(),
  delivery_method: z.string().nullable(),
  delivery_address: z.string().nullable(),
  protection_plan: z.string(),
  approved_at: z.string().nullable(),
  declined_at: z.string().nullable(),
  cancelled_at: z.string().nullable(),
  cancelled_by: z.string().nullable(),
  cancellation_reason: z.string().nullable(),
  started_at: z.string().nullable(),
  completed_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const publicBookingsInsertSchema = z.object({
  id: z.string().optional(),
  listing_id: z.string(),
  renter_id: z.string(),
  owner_id: z.string(),
  start_time: z.string(),
  end_time: z.string(),
  status: z
    .union([
      z.literal("requested"),
      z.literal("approved"),
      z.literal("declined"),
      z.literal("auto_declined"),
      z.literal("active"),
      z.literal("completed"),
      z.literal("cancelled"),
      z.literal("disputed"),
      z.literal("resolved"),
    ])
    .optional(),
  payment_authorized: z.boolean().optional(),
  subtotal: z.number(),
  service_fee: z.number(),
  delivery_fee: z.number().optional(),
  protection_fee: z.number().optional(),
  deposit_amount: z.number().optional(),
  total_amount: z.number(),
  owner_payout: z.number(),
  currency: z.string().optional(),
  delivery_method: z.string().optional().nullable(),
  delivery_address: z.string().optional().nullable(),
  protection_plan: z.string().optional(),
  approved_at: z.string().optional().nullable(),
  declined_at: z.string().optional().nullable(),
  cancelled_at: z.string().optional().nullable(),
  cancelled_by: z.string().optional().nullable(),
  cancellation_reason: z.string().optional().nullable(),
  started_at: z.string().optional().nullable(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicBookingsUpdateSchema = z.record(z.string(), z.any());

export const publicTransactionsRowSchema = z.object({
  id: z.string(),
  booking_id: z.string(),
  type: z.union([
    z.literal("pre_auth"),
    z.literal("capture"),
    z.literal("payout"),
    z.literal("refund"),
    z.literal("partial_refund"),
  ]),
  status: z.union([
    z.literal("pending"),
    z.literal("authorized"),
    z.literal("completed"),
    z.literal("failed"),
    z.literal("cancelled"),
    z.literal("refunded"),
  ]),
  amount: z.number(),
  currency: z.string(),
  payway_tran_id: z.string().nullable(),
  payway_status: z.string().nullable(),
  metadata: jsonSchema,
  processed_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const publicTransactionsInsertSchema = z.object({
  id: z.string().optional(),
  booking_id: z.string(),
  type: z.union([
    z.literal("pre_auth"),
    z.literal("capture"),
    z.literal("payout"),
    z.literal("refund"),
    z.literal("partial_refund"),
  ]),
  status: z
    .union([
      z.literal("pending"),
      z.literal("authorized"),
      z.literal("completed"),
      z.literal("failed"),
      z.literal("cancelled"),
      z.literal("refunded"),
    ])
    .optional(),
  amount: z.number(),
  currency: z.string().optional(),
  payway_tran_id: z.string().optional().nullable(),
  payway_status: z.string().optional().nullable(),
  metadata: jsonSchema.optional(),
  processed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicTransactionsUpdateSchema = z.record(z.string(), z.any());

export const publicMessageThreadsRowSchema = z.object({
  id: z.string(),
  listing_id: z.string().nullable(),
  booking_id: z.string().nullable(),
  participant_ids: z.array(z.string()),
  last_message_at: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const publicMessageThreadsInsertSchema = z.object({
  id: z.string().optional(),
  listing_id: z.string().optional().nullable(),
  booking_id: z.string().optional().nullable(),
  participant_ids: z.array(z.string()),
  last_message_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicMessageThreadsUpdateSchema = z.record(z.string(), z.any());

export const publicMessagesRowSchema = z.object({
  id: z.string(),
  thread_id: z.string(),
  sender_id: z.string(),
  content: z.string(),
  read_at: z.string().nullable(),
  created_at: z.string(),
});

export const publicMessagesInsertSchema = z.object({
  id: z.string().optional(),
  thread_id: z.string(),
  sender_id: z.string(),
  content: z.string(),
  read_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
});

export const publicMessagesUpdateSchema = z.record(z.string(), z.any());

export const publicReviewsRowSchema = z.object({
  id: z.string(),
  booking_id: z.string(),
  listing_id: z.string(),
  reviewer_id: z.string(),
  target_id: z.string(),
  rating: z.number(),
  comment: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string(),
});

export const publicReviewsInsertSchema = z.object({
  id: z.string().optional(),
  booking_id: z.string(),
  listing_id: z.string(),
  reviewer_id: z.string(),
  target_id: z.string(),
  rating: z.number(),
  comment: z.string().optional().nullable(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicReviewsUpdateSchema = z.record(z.string(), z.any());

export const publicNotificationsRowSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  type: z.string(),
  title: z.string(),
  body: z.string().nullable(),
  data: jsonSchema,
  read_at: z.string().nullable(),
  created_at: z.string(),
});

export const publicNotificationsInsertSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  type: z.string(),
  title: z.string(),
  body: z.string().optional().nullable(),
  data: jsonSchema.optional(),
  read_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
});

export const publicNotificationsUpdateSchema = z.record(z.string(), z.any());

export const publicSearchListingsArgsSchema = z.object({
  search_query: z.string().optional().nullable(),
  search_lat: z.number().optional().nullable(),
  search_lng: z.number().optional().nullable(),
  search_radius_km: z.number().optional(),
  category_slug: z.string().optional().nullable(),
  listing_type: z.string().optional().nullable(),
  price_min: z.number().optional().nullable(),
  price_max: z.number().optional().nullable(),
  sort_by: z.string().optional(),
  result_limit: z.number().optional(),
  result_offset: z.number().optional(),
});

export const publicSearchListingsReturnsSchema = z.array(
  z.object({
    id: z.string(),
    title: z.string(),
    description: z.string().nullable(),
    type: z.union([z.literal("offer"), z.literal("request")]),
    price_daily: z.number(),
    deposit_amount: z.number(),
    currency: z.string(),
    owner_id: z.string(),
    owner_display_name: z.string(),
    owner_avatar_url: z.string().nullable(),
    owner_rating: z.number(),
    owner_verified: z.boolean(),
    listing_rating: z.number(),
    review_count: z.number(),
    distance_km: z.number().nullable(),
    first_image_url: z.string().nullable(),
    created_at: z.string(),
  })
);

export type Json = z.infer<typeof jsonSchema>;
export type PublicProfilesRow = z.infer<typeof publicProfilesRowSchema>;
export type PublicProfilesInsert = z.infer<typeof publicProfilesInsertSchema>;
export type PublicProfilesUpdate = z.infer<typeof publicProfilesUpdateSchema>;
export type PublicCategoriesRow = z.infer<typeof publicCategoriesRowSchema>;
export type PublicCategoriesInsert = z.infer<typeof publicCategoriesInsertSchema>;
export type PublicCategoriesUpdate = z.infer<typeof publicCategoriesUpdateSchema>;
export type PublicListingsRow = z.infer<typeof publicListingsRowSchema>;
export type PublicListingsInsert = z.infer<typeof publicListingsInsertSchema>;
export type PublicListingsUpdate = z.infer<typeof publicListingsUpdateSchema>;
export type PublicListingMediaRow = z.infer<typeof publicListingMediaRowSchema>;
export type PublicListingMediaInsert = z.infer<typeof publicListingMediaInsertSchema>;
export type PublicListingMediaUpdate = z.infer<typeof publicListingMediaUpdateSchema>;
export type PublicAvailabilityRow = z.infer<typeof publicAvailabilityRowSchema>;
export type PublicAvailabilityInsert = z.infer<typeof publicAvailabilityInsertSchema>;
export type PublicAvailabilityUpdate = z.infer<typeof publicAvailabilityUpdateSchema>;
export type PublicBookingsRow = z.infer<typeof publicBookingsRowSchema>;
export type PublicBookingsInsert = z.infer<typeof publicBookingsInsertSchema>;
export type PublicBookingsUpdate = z.infer<typeof publicBookingsUpdateSchema>;
export type PublicTransactionsRow = z.infer<typeof publicTransactionsRowSchema>;
export type PublicTransactionsInsert = z.infer<typeof publicTransactionsInsertSchema>;
export type PublicTransactionsUpdate = z.infer<typeof publicTransactionsUpdateSchema>;
export type PublicMessageThreadsRow = z.infer<typeof publicMessageThreadsRowSchema>;
export type PublicMessageThreadsInsert = z.infer<typeof publicMessageThreadsInsertSchema>;
export type PublicMessageThreadsUpdate = z.infer<typeof publicMessageThreadsUpdateSchema>;
export type PublicMessagesRow = z.infer<typeof publicMessagesRowSchema>;
export type PublicMessagesInsert = z.infer<typeof publicMessagesInsertSchema>;
export type PublicMessagesUpdate = z.infer<typeof publicMessagesUpdateSchema>;
export type PublicReviewsRow = z.infer<typeof publicReviewsRowSchema>;
export type PublicReviewsInsert = z.infer<typeof publicReviewsInsertSchema>;
export type PublicReviewsUpdate = z.infer<typeof publicReviewsUpdateSchema>;
export type PublicNotificationsRow = z.infer<typeof publicNotificationsRowSchema>;
export type PublicNotificationsInsert = z.infer<typeof publicNotificationsInsertSchema>;
export type PublicNotificationsUpdate = z.infer<typeof publicNotificationsUpdateSchema>;
export type PublicSearchListingsArgs = z.infer<typeof publicSearchListingsArgsSchema>;
export type PublicSearchListingsReturns = z.infer<typeof publicSearchListingsReturnsSchema>;
